name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  project_name:
    description: 'The name of the project'
    required: true
    default: 'tauri-app'
  identifier:
    description: 'The identifier for the project'
    required: false
    default: 'com.tauri-app.app'
  version:
    description: 'The version for the project'
    required: false
    default: '0.1.0'
  template:
    description: 'The template to use for the project'
    required: false
    default: 'vanilla'
  manager:
    description: 'The package manager to use'
    required: false
    default: 'npm'
  frontend_dist:
    description: 'The frontend distribution directory'
    required: false
    default: '../dist'
  output_dir:
    description: 'The output directory of tauri build'
    required: false
    default: 'tauri-build'
  icon:
    description: 'The icon for the project'
    required: false
  tauri_conf_json:
    description: 'Optional tauri.conf.json file overwrite'
    required: false
  cargo_toml:
    description: 'Optional Cargo.toml file overwrite'
    required: false
  build_rs:
    description: 'Optional build.rs file overwrite'
    required: false
  lib_rs:
    description: 'Optional lib.rs file overwrite'
    required: false
  main_rs:
    description: 'Optional main.rs file overwrite'
    required: false

runs:
  using: node20
  main: dist/index.js
